In [37]:
import numpy as np

# Tensores

Las estructuras basicas de datos en Deep Learning son los tensores
que son basicamente arrays n-dimensionales, por ejemplo una matriz
es un tensor 2-dimensional.

## Escalar

In [27]:
# Vamos a crear un escalar (tensor 0-dimensional) en numpy:

escalar = np.array(27)
print("Tensor: " + str(escalar)) # Nos muestra el escalar que acabamos de crear
print("Dimension: " + str(escalar.ndim)) # Nos muestra las dimensiones (el rango o los ejes) del tensor que hemos creado

Tensor: 27
Dimension: 0


## Vector

In [28]:
# Vamos a crear un vector (tensor 1-dimensional) en numpy:

vector = np.array([1,2,3,4]) # Creamos un vector 4-dimensional
print("Tensor: " + str(vector))
print("Dimension: " + str(vector.ndim))

Tensor: [1 2 3 4]
Dimension: 1


## Matriz

In [29]:
# Vamos a crear una matriz (tensor 2-dimensional) en numpy:

matriz = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])
print("Tensor: \n\n " + str(matriz))
print("\n Dimension: " + str(matriz.ndim))

Tensor: 

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Dimension: 2


## Tensor 3-dimensional

In [46]:
#Vamos a crear un tensor 3-dimensional en numpy:

tensor3d = np.array([  [[1, 1, 2, 34, 0],
                       [6, 2, 3, 35, 1],
                       [7, 3, 4, 36, 2]],
              
                       [[2, 1, 2, 34, 0],
                       [6, 2, 3, 35, 1],
                       [7, 3, 4, 36, 2]],
                
                       [[3, 1, 2, 34, 0],
                       [6, 2, 3, 35, 1],
                       [7, 3, 4, 36, 2]]   ])

print("Tensor: \n\n " + str(tensor3d))
print("\n Dimension: " + str(tensor3d.ndim))

Tensor: 

 [[[ 1  1  2 34  0]
  [ 6  2  3 35  1]
  [ 7  3  4 36  2]]

 [[ 2  1  2 34  0]
  [ 6  2  3 35  1]
  [ 7  3  4 36  2]]

 [[ 3  1  2 34  0]
  [ 6  2  3 35  1]
  [ 7  3  4 36  2]]]

 Dimension: 3


## Tensores n-dimensionales

Puede que nos hayamos dado cuenta de un patron. Aumentar de dimension un tensor no es mas
que meter varios tensores de la dimension anterior en un array.

# Manipulando tensores

Para **crear** tensores es como hemos visto arriba:

In [45]:
tensor = np.array([1,2])
print(tensor)

[1 2]


Para ver la **forma** que tiene un tensor:

In [42]:
forma = tensor3d.shape
print(forma)

(3, 3, 5)


Para ver el **tipo** de un tensor:

In [44]:
tipo = tensor3d.dtype
print(tipo)

int64


## Slicing

Es un slicing normal y corriente, pero hay que tener en cuenta la n-dimensionalidad del tensor

In [56]:
tensor3d_slice1 = tensor3d[0:1,0:1,0:2] # De la primera matriz coge la primera fila, los dos primeros elementos.
tensor3d_slice2 = tensor3d[0:2,0:2,0:2] # De las 2 primeras matrices coge las 2 primeras filas, y de estas los dos primeros elementos.
tensor3d_slice3 = tensor3d[0:3,0:1,0:2] # De las 3 primeras matrices coge la primera fila, los dos primeros elementos.

print("\n")
print("tensor3d_slice1: \n")
print(tensor3d_slice1)
print("---------------------")
print("tensor3d_slice2: \n")
print(tensor3d_slice2)
print("---------------------")
print("tensor3d_slice3: \n")
print(tensor3d_slice3)



tensor3d_slice1: 

[[[1 1]]]
---------------------
tensor3d_slice2: 

[[[1 1]
  [6 2]]

 [[2 1]
  [6 2]]]
---------------------
tensor3d_slice3: 

[[[1 1]]

 [[2 1]]

 [[3 1]]]


Los indices del slicing se van seleccionando de fuera hacia dentro.
en el ejemplo ` tensor3d[0:3,0:1,0:2] ` hemos seleccionado las 3 primeras matrices,
de estas tres matrices hemos cogido de cada una la primera fila, y de cada una de las filas que
hemos cogido solo nos quedamos con los 2 primeros elementos.

En Deep Learning consideramos el primer indice (el primer eje) como el **eje de los ejemplos**
,ya que es el indice del conjunto mas exterior que engloba todos los datos.

## Lotes de datos

Normalmente en Deep Learning los ejemplos se usan por **lotes** (batchs en ingles), es decir,
separan todos los ejemplos que tenemos en dos o mas lotes.