# ***INDEX***
---

## 1. **[Introducing Neural Networks](#Introducing-Neural-Networks)**
### 1.1. [Perceptron](#Perceptron)
### 1.2. [Neural Network](#Neural-Network)
### 1.3. [How does learning takes place?](#How-does-learning-take-place?)
---
## 2. **[Tensorflow](#TensorFlow)**
### 2.1. [Constants](#Constants-(Tensors))
### 2.2. [Tensor operations](#Tensor-operations)
---
## 3. **[Keras](#Keras)**
### 3.1. [Building Neural Networks](#Building-Neural-Networks)

In this intro, I will not be explaining lot of maths, I will just show the formulas and some stuff, becaus I just want this to be an overview.

# **Introducing Neural Networks**





Before we introduce NN, we need to understand what is a perceptron.

## **Perceptron**

It is a "neuron".  
Each unit that the neural network has is a perceptron:

![perceptron image](https://github.com/theesmoxDEV/ML-AI/blob/master/Intro%20to%20TensorFlow%20%26%20Keras/Perceptron_diagram.png?raw=1)



It has the inputs (the training data), weights associated to those inputs, a bias, a sum, an activation function and an output (our prediction).



Mathematically, we can explain this diagram like this:

$y = \varphi(x_0w_0 + \sum_{i=1}^{n} x_iw_i)$  

---

this is the same as  

$y = \varphi(x_0w_0 + X^{T}W)$  
 
 ---

Where:

* $X$ are the inputs:
$
\left(\begin{array}{cc} 
x_i\\
...\\
x_n
\end{array}\right)
$
---
* $W$ are the weights:
$
\left(\begin{array}{cc} 
w_i\\
...\\
w_n
\end{array}\right)
$
---
* $\varphi$ is the activation function: there are lots of different functions, the most usual functions are

![usual functions image](https://github.com/theesmoxDEV/ML-AI/blob/master/Intro%20to%20TensorFlow%20%26%20Keras/usual_activation_functions.png?raw=1)

---
* $x_0w_0$ is the bias: Usually $x_0=-1$ and $w_0=1$, but it could be $x_0=1$ and $w_0=-1$ too.


## **Neural Network**

It is like a brain.  
A simple neural network (NN) has an input layer, a hidden layer and an output layer.

In this image we se a fully connected NN, with 4 input units, 5 hidden units and 1 output unit:

![neural network image](https://github.com/theesmoxDEV/ML-AI/blob/master/Intro%20to%20TensorFlow%20%26%20Keras/neural_network.png?raw=1)

Each unit is a perceptron with its own weights.
As we see, as in the perceptron, we have a sum and an activation function in each perceptron of each layer.  

I will not go too deep in this structure as that is no my objective in this intro. I just want to show an overview.

## **How does learning take place?**


To fully understand the learning process requires tons of math. I will try to simplify it as much as I can, to have a vision of how can it be.

### **The basis**

Basically, the learning process consists in **updating the weights of the perceptron** (or peceptrons, if we are training a Neural Network).

To train a perceptron we need **training data** and **training targets**:

 * **Training data:** it is the data we use to feed our perceptron. The model we create tries to "fit" to this data.
 * **Training target:** it is usually included in the training data. The training target is the "thing" or the "label" we want our perceptron to predict. **It is the output we want to achieve updating the weights.**

---

**Example:** Trying to learn OR operation

We could have the following **training data** [ [1, 1], [1, 0], [0, 1], [0, 0] ] associated with this **training targets** [ [1], [1], [1], [0] ].  
For those who don't know what the OR operation does, **it returns 1 when there is one or more 1s**. So, associating the training data and the training targets, we have:  

**[1] [1] [1]**  
**[1] [0] [1]**  
**[0] [1] [1]**  
**[0] [0] [0]** , because if we have [1] [1], we expect a 1, if we have [0] [0], we expect a 0, etc.  

---

**Keep in mind** that we refer to both (training data and targets) as training data.

### **Learning in perceptrons**

### **Learning Neural Network**

# **TensorFlow**

As described in www.tensorflow.org:  

>"**TensorFlow is an end-to-end open source platform for machine learning.** It has a comprehensive, flexible ecosystem of tools, libraries and community resources that lets researchers push the state-of-the-art in ML and developers easily build and deploy ML powered applications."

But basically, what bothers us right now, is that it is a **tool to manage tensors** (as all the data we feed into neural networks are tensors).

## **Constants (Tensors)**

Tensors are n-dimensional objects.  
A scalar is a 0-dimensional tensor, a vector is a 1-dimensional tensor, a matrix is a 2-dimensional tensor, etc. 

In [0]:
# Importing all the necessary things

%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

TensorFlow 2.x selected.


In [0]:
constant_string = tf.constant("NAME") # You don't have to specify the type, it
                                      # is infered from the tensor content
        
constant_number = tf.constant(100, dtype=tf.int32)

print(constant_string)
print(constant_number)

tf.Tensor(b'NAME', shape=(), dtype=string)
tf.Tensor(100, shape=(), dtype=int32)


As we see in the parameter "shape", it is empty. That means that we are using scalars. In the next example we will define multi-dimensional tensors.

In [0]:
tensor_1d = tf.constant([1,2,3,4]) # vector

tensor_2d = tf.constant([[1,2,3],[4,5,6]]) # matrix

tensor_3d = tf.constant([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]]) # cube

print("tensor_1d shape: {}".format(tensor_1d.shape))
print("----------------------------------------------")
print("tensor_2d shape: {}".format(tensor_2d.shape))
print("----------------------------------------------")
print("tensor_3d shape: {}".format(tensor_3d.shape))

tensor_1d shape: (4,)
----------------------------------------------
tensor_2d shape: (2, 3)
----------------------------------------------
tensor_3d shape: (2, 2, 3)


Take in count that we have used ```tf.shape``` to check the tensor shape.

What can we see here?, simplifying we have:

*   **tensor_1d**: Its shape tells us that it has 4 objects, and this objects doesn't have any elements (1 dimension).
*   **tensor_2d**: Its shape tells us that it has 2 objects, and each object has 3 elements (it is 2-dimensional).
*   **tensor_3d**: Its shape tells us that it has 2 objects, with 2 elements each and each element has 3 components (it is 3-dimensional).

  We check this using ```tf.rank()``` :


In [0]:
print("tensor_1d is a tensor with {} dimensions".format(tf.rank(tensor_1d)))
print("tensor_2d is a tensor with {} dimensions".format(tf.rank(tensor_2d)))
print("tensor_3d is a tensor with {} dimensions".format(tf.rank(tensor_3d)))

tensor_1d is a tensor with 1 dimensions
tensor_2d is a tensor with 2 dimensions
tensor_3d is a tensor with 3 dimensions


## **Tensor operations**

We will try to compute this operation:

![add graph image](https://github.com/theesmoxDEV/ML-AI/blob/master/Intro%20to%20TensorFlow%20%26%20Keras/add-graph.png?raw=1)

In [0]:
# Nodes in the graph:
a = tf.constant(1)
b = tf.constant(2)

# Addition of the nodes:
c = tf.add(a,b)

Lets try a more complex operation:

![computation graph image](https://github.com/theesmoxDEV/ML-AI/blob/master/Intro%20to%20TensorFlow%20%26%20Keras/computation-graph.png?raw=1)

We will see two approaches:

In [0]:
## APPROACH 1 ##
# We simply perform the operations

# Initial nodes in the graph:
a2 = tf.constant(1) 
b2 = tf.constant(2)

# Intermediate nodes:
c2 = tf.add(a2,b2)
d2 = tf.subtract(b2,1)

# Final node:
e2 = tf.multiply(c2,d2) # element-wise matrices multiplication

print("Result from approach 1: {}".format(e2))

## APPROACH 2 ##
# We define a function to compute the operation

def operation(a,b): # We suppose that 'a' and 'b' are tensors
  c,d = tf.add(a,b), tf.subtract(b,1)
  return tf.multiply(c,d)

print("Result from approach 2: {}".format(operation(a2,b2)))

Result from approach 1: 3
Result from approach 2: 3


We can multiply matrices using ```tf.matmul```.
Keep in mind that shape of matrices have to be transposed.
Here we have two different ways of calculating it:

In [0]:
constant1 = tf.constant([[1,2,3]], shape = (3,1))
constant2 = tf.constant([[3,2,1]], shape = (1,3))
print(tf.matmul(constant1, constant2))

print("----------------------------------------")

constant3 = tf.constant([[1,2,3]])
constant4 = tf.constant([[3,2,1]])
print(tf.matmul(constant3, constant4, transpose_a=True))

tf.Tensor(
[[3 2 1]
 [6 4 2]
 [9 6 3]], shape=(3, 3), dtype=int32)
----------------------------------------
tf.Tensor(
[[3 2 1]
 [6 4 2]
 [9 6 3]], shape=(3, 3), dtype=int32)


# **Keras**

As described in www.keras.io :

>**Keras is a high-level neural networks API**, written in Python and capable of running on top of TensorFlow, CNTK, or Theano. It was developed with a focus on enabling fast experimentation.

But, basically, it is a **tool to build neural networks**.


We will use the Keras API for easy-build neural networks. It is implemented as
```tf.keras``` (we could use it outside TensorFlow, but this is easier if we are going to use TensorFlow). Now, with TensorFlow 2.0, there are two main ways of building a 
simple neural net:

*   Using ```tf.keras.Sequential``` (the "classic" way)
*   Using the ***Keras functional API*** (the "new" way)


> To keep in mind: The tf.keras version in the latest TensorFlow release might not be the same as the latest keras version from PyPI. Check tf.keras.version.


## **Building Neural Networks**

### **tf.keras.Sequential**

This is the "classic way" of building a NN. 
We are going to build a simple fully-connected NN with 1 hidden layer:

In [0]:
from tensorflow.keras import layers

model = tf.keras.Sequential()
# Adds a densely-connected layer with 64 units to the model,
# with the input data shape -> (32,)
model.add(layers.Dense(64, activation='relu', input_shape=(32,)))
# Add another:
model.add(layers.Dense(64, activation='relu'))
# Add an output layer with 10 output units:
model.add(layers.Dense(10))

This is the same as:

In [0]:
model = tf.keras.Sequential([
# Adds a densely-connected layer with 64 units to the model,
# with the input data shape -> (32,)
layers.Dense(64, activation='relu', input_shape=(32,)),
# Add another (we don't need the input shape because it is
# a hidden layer):
layers.Dense(64, activation='relu'),
# Add an output layer with 10 output units:
layers.Dense(10)])

The base of a NN is the model object (in this case we are using ```Sequential()```), were we add Layers and more things
that we will see later.

### **Keras functional API**

The Keras functional API is a (new) way to create models that are more flexible than the ```tf.keras.Sequential``` API

In [0]:
# We create the input data , with shape -> (32,)
inputs = keras.Input(shape=(32,))
# We create a densely-connected layer with 64 units to the model
dense = layers.Dense(64, activation='relu')
# We combine the input shape and the dense layer to build our input layer
# and store it in x
x = dense(inputs)
# We add another dense layer with 64 units to x
x = layers.Dense(64, activation='relu')(x)
# We create the output layer with 10 units by adding one more layer to x
outputs = layers.Dense(10)(x)
model = keras.Model(inputs=inputs, outputs=outputs, name='mnist_model')

### **Compiling and training the model**

Once we have the model (it doesn't matter which way we choose), we have to compile it. This is the moment when we specify optimizers, the loss function, etc (we will cover these things later on):

In [0]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.01), 
              loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

After compiling our model, we can train it with data. We can use either NumPy
or a ```tf.data``` instance:

#### **Using NumPy**

For small datasets, use in-memory NumPy arrays to train and evaluate a model. The model is "fit" to the training data using the fit method:

In [0]:
import numpy as np

# We load our data and our targets(labels)
data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))

# We train our model
model.fit(data, labels, epochs=10, batch_size=32)

#### **Using tf.data**
Use the Datasets API to scale to large datasets or multi-device training. Pass a tf.data.Dataset instance to the fit method:

In [0]:
# Instantiates a toy dataset instance:
dataset = tf.data.Dataset.from_tensor_slices((data, labels))
dataset = dataset.batch(32)

model.fit(dataset, epochs=10)

### **Evaluating our model**

Once we have our model trained, we can test its accuracy.

#### **Using NumPy**

In [0]:
# With Numpy arrays
data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))

model.evaluate(data, labels)

#### **Using tf.data**

In [0]:
# With a Dataset
dataset = tf.data.Dataset.from_tensor_slices((data, labels))
dataset = dataset.batch(32)

model.evaluate(dataset)


### **Predicting**

When we are happy with our model's accuracy, we can start predicting on new data. This is as simple as:

In [0]:
result = model.predict(data)
print(result)